### ISSUE TITLE
Hvala!

### ISSUE THREAD

**Issue by mariokostelac** [senko/fiskal-hr#1]
Samo sam htio reci hvala. Ustedio si mi jaaaako puno vremena.

Ako imas ideju kako ti netko moze pomoci da ovo ostane mainteineano, javi.

**Comment by senko** [comment]
Super, drago mi je da je korisno!

Javi bilo kakve probleme ako naiđeš ili ako je nešto zbunjujuće itd. Trenutno ovo koristimo na jednom projektu koji je u fazi testiranja (1.1. taj projekt kreće s produkcijom) pa još možda bude malo peglanja ako naletimo na probleme kad se prebacimo na produkcijske certifikate.

Planiram aktivno održavati paket pošto ću ga i osobno koristiti na bar jednom (koji sam spomenuo) ili dva (vjerojatno u skorijoj budućnosti) projekta, ako ne i šire.
