### ISSUE TITLE
Neuspjesno pokretanje projekta

### ISSUE THREAD

**Issue by franepetrekovic** [senko/fiskal-hr#2]
Bok Senko,

Prvo da Vam se zahvalim na odlicnom repozitoriju i detaljnim docsima. Pocetnik sam te se ispricavam ako sam napravio nekakav previd.

Imam problem prilikom pozivanja testne "echo" metode koji mi se pojavljuje neovisno koristim li svoje certfikate ili ove Vase iz /testdata. Samo sam iskopirao sam ovih par linija koda iz [testing integration paragrafa](https://github.com/senko/fiskal-hr/blob/main/doc/integration.md#testing-integration) u kreirani main.py u rootu projekta te referencirao prilozene certifikate.

```
from fiskalhr.invoice import Invoice, InvoiceNumber
from fiskalhr.ws import FiskalClient
from fiskalhr.signature import Signer, Verifier
from fiskalhr import Invoice

TEST_WSDL = "testdata/ws/wsdl/FiskalizacijaService.wsdl"
CLIENT_COMBINED_PLAINTEXT_KEY = "testdata/client_combined_plaintext_key.crt"
CLIENT_CRT = "testdata/client.crt"
ROOT_CA_CRT = "testdata/root_ca.crt"

signer = Signer(CLIENT_COMBINED_PLAINTEXT_KEY)
verifier = Verifier(CLIENT_CRT, [ROOT_CA_CRT])
fiskal_client = FiskalClient(ROOT_CA_CRT, TEST_WSDL, signer, verifier)  
fiskal_client.test_service()
```

Cim pokrenem sa ``python main.py``, odmah mi na prvoj liniji prilikom importanja pukne s:
```
S C:\Users\OneDrive\Desktop\fiskal-hr> python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from fiskalhr.invoice import Invoice, InvoiceNumber
  File "C:\Users\OneDrive\Desktop\fiskal-hr\fiskalhr\invoice.py", line 10, in <module>
    from .enums import PaymentMethod, SequenceScope
  File "C:\Users\OneDrive\Desktop\fiskal-hr\fiskalhr\enums.py", line 321, in <module>
    ResponseErrorEnum._value_docstrings = get_response_error_enum_docstrings()
  File "C:\Users\OneDrive\Desktop\fiskal-hr\fiskalhr\meta.py", line 38, in get_response_error_enum_docstrings
    enums = match_enums.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
PS C:\Users\OneDrive\Desktop\fiskal-hr>
```

Znate li mozda gdje grjesim? Unaprijed hvala na odgovoru.

**Comment by senko** [comment]
Hmm greška više zvuči kao nekompatibilinost Python verzija. Koju verziju Pythona koristite?

Softver je testiran na Pythonu 3.8, 3.9 i 3.10. Moguće je da radi i sa drugim sličnim verzijama ali to nisam 100% siguran, možda ima ovakvih problema. Ako ste vi na nekoj drugoj verziji, mogu probati s tim pa vidjeti ima li neko jednostavno rješenje.

**Comment by damjanvucina** [comment]
@senko Inicijalno verziju 3.7.9, sad sam isprobao sa 3.9.0, baca istu gresku. Probao upgradeati i pip na 23.1.2, i dalje throwa

**Comment by franepetrekovic** [comment]
@senko inicijalno verziju 3.7.9, sad sam isprobao sa 3.9.0, baca istu gresku. Probao upgradeati i pip na 23.1.2, i dalje throwa

**Comment by senko** [comment]
Probao sam sa 3.9.13, prolazi mi, odnosno pukne kasnije ali ne baca ovu grešku koja se vama događa. Ovako to izgleda kod mene:

```
Traceback (most recent call last):
  File "C:\Users\User\Projects\fiskal-hr\main.py", line 14, in <module>
    fiskal_client.test_service()
  File "C:\Users\User\Projects\fiskal-hr\fiskalhr\ws.py", line 96, in test_service
    response = self.client.service.echo(test_message)
  File "C:\Users\User\Projects\venv\lib\site-packages\zeep\proxy.py", line 46, in __call__
    return self._proxy._binding.send(
  File "C:\Users\User\Projects\venv\lib\site-packages\zeep\wsdl\bindings\soap.py", line 127, in send
    response = client.transport.post_xml(options["address"], envelope, http_headers)
  File "C:\Users\User\Projects\venv\lib\site-packages\zeep\transports.py", line 108, in post_xml
    return self.post(address, message, headers)
  File "C:\Users\User\Projects\venv\lib\site-packages\zeep\transports.py", line 74, in post
    response = self.session.post(
  File "C:\Users\User\Projects\venv\lib\site-packages\requests\sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "C:\Users\User\Projects\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\User\Projects\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\User\Projects\venv\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='cistest.apis-it.hr', port=8449): Max retries exceeded with url: /FiskalizacijaServiceTest (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))
```

Ova greška je očekivana jer se certifikati ne poklapaju. Ali onaj dio koji kod vas puca je ranije, prilikom inicijalizacije fiskal-hr koda, prije nego dođe do echo servisa.

Jeste li možda editirali enum.py ? Konkretno tamo postoje 2 komentara koja se kasnije parsiraju da bi se pokazala ljepša dokumentacija koda, taj dio nije baš najsretnije riješen ali u pravilu ne bi trebao stvarati probleme.

(Ne koristim Windowse pa nažalost ne mogu puno pomoći sa debuggiranjem)
